FROM node:16-alpine as build

WORKDIR /frontend

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

FROM nginx

COPY --from=build /frontend/build /usr/share/nginx/html

COPY --from=build /frontend/nginx.default.conf /etc/nginx/conf.d/default.conf