version: "3.8"
services:
  api:
    stdin_open: true
    tty: true
    build:  
      context: ./api
      dockerfile: Dockerfile.prod
    ports: 
    - "5000:5000"
    environment: 
      FLASK_ENV: production
  frontend:
    stdin_open: true
    tty: true
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports: 
      - "8080:80"
    depends_on: 
      - api