version: "3.8"
services:
  api:
    stdin_open: true
    tty: true
    build:  
      context: ./api
      dockerfile: Dockerfile.prod
    ports: 
    - "5000:5000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  frontend:
    stdin_open: true
    tty: true
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports: 
      - "8080:80"
    depends_on: 
      - api
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod: