version: "3.9"
services:
  api:
    build:  
      context: ./api
    image: munziu263/taskhub-api
    ports: 
    - "5000:5000"
    volumes: 
    - ./api:/api/
    environment: 
      FLASK_ENV: production
  frontend:
    build: 
      context: ./frontend
    image: munziu263/taskhub-frontend
    volumes: 
    - ./frontend:/frontend/
    ports: 
      - "3000:3000"
    depends_on: 
      - api