version: "3.8"
services:
  api:
    stdin_open: true
    tty: true
    build:  
      context: ./api
      dockerfile: Dockerfile.dev
    volumes: 
    - ./api:/api
    ports: 
    - "5000:5000"
    environment: 
      FLASK_ENV: development
      FLASK_APP: wsgi
  frontend:
    stdin_open: true
    tty: true
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes: 
    - ./frontend:/frontend
    ports: 
      - "3000:3000"
    depends_on: 
      - api