version: "3.8"
services:
  api:
    stdin_open: true
    tty: true
    build:  
      context: ./api
    ports: 
    - "5000:5000"
    volumes: 
    - ./api:/api/
    environment: 
      FLASK_ENV: production
  frontend:
    stdin_open: true
    tty: true
    build: 
      context: ./frontend
    volumes: 
    - ./frontend:/frontend/src
    ports: 
      - "3000:3000"
    depends_on: 
      - api